### ISSUE TITLE
I want to be able to portforward

### ISSUE THREAD

**Issue by owodunni** [hansfilipelo/dockrun#1]
Hi!

Great repository.

I realy need to be able to specify the portforward option. For example if I develop with node and I don't want to install node then I want to open node with port forwarding like this:

 docker run -v ~/pathToCode:/code -p 8080:8080 -it node:8 bash

**Comment by hansfilipelo** [comment]
This is outside the scope of this project. It is more a simple abstraction for installing tools within a container instead of on your host system (`brew install TOOL` or `apt install TOOL`). 

I'd recommend you use a Dockerfile instead of a "clean" Node container and an interactive shell for your Node app.

Argument forwarding to tools running within the container is within the scope of this project though, and will be added.
